# Generated by Django 5.1.7 on 2025-04-14 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumechecker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='job_title',
        ),
    ]
